# Generated by Django 5.2.9 on 2026-02-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resource', '0003_alter_location_id_alter_resource_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
