# Generated by Django 5.2.9 on 2026-02-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_alter_action_id_alter_action_name_alter_classroom_id_and_more'),
        ('TaskManager', '0002_computer_tariff_zone_payment_session_computer_zone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='class_room',
        ),
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Баланс (грн)'),
        ),
        migrations.AlterField(
            model_name='action',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(choices=[('MC', "Керування комп'ютерами"), ('MT', 'Керування тарифами'), ('MS', 'Керування сесіями'), ('VS', 'Перегляд статистики'), ('CB', 'Створення бронювань'), ('MB', 'Керування бронюваннями')], default='VS', help_text='Введіть назву дії', max_length=100, verbose_name='Дозволена дія'),
        ),
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='ClassRoom',
        ),
    ]
