# Generated by Django 5.2.9 on 2026-02-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_remove_classroom_subjects_remove_profile_class_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='avatars/%Y/%m/', verbose_name='Аватарка'),
        ),
    ]
