# Generated by Django 5.2.9 on 2026-02-12 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Номер/Назва ПК')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адреса')),
                ('status', models.CharField(choices=[('FR', 'Вільний'), ('BS', 'Зайнятий'), ('MT', 'Технічні роботи')], default='FR', max_length=2, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва тарифу')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Ціна за годину (грн)')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва зони')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума')),
                ('payment_type', models.CharField(choices=[('DP', 'Поповнення рахунку'), ('SP', 'Оплата сесії'), ('RF', 'Повернення коштів')], max_length=2, verbose_name='Тип платежу')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата транзакції')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Початок сесії')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Кінець сесії')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Вартість')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskManager.computer', verbose_name="Комп'ютер")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клієнт')),
                ('tariff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TaskManager.tariff', verbose_name='Тариф')),
            ],
        ),
        migrations.AddField(
            model_name='computer',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskManager.zone', verbose_name='Ігрова зона'),
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
