# Generated by Django 5.2.9 on 2026-02-12 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0002_computer_tariff_zone_payment_session_computer_zone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Час початку')),
                ('duration', models.IntegerField(help_text='Тривалість у годинах', verbose_name='Тривалість')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('approved', 'Підтверджено'), ('rejected', 'Відхилено')], default='pending', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskmanager_bookings', to='TaskManager.computer', verbose_name="Комп'ютер")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskmanager_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
        ),
    ]
