# Generated by Django 5.2.9 on 2026-02-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0003_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='status',
            field=models.CharField(choices=[('FR', 'Вільний'), ('BS', 'Зайнятий'), ('MT', 'Технічні роботи'), ('BK', 'Заброньовано')], default='FR', max_length=2, verbose_name='Статус'),
        ),
    ]
