# Generated by Django 5.2.9 on 2026-02-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0004_alter_computer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='x_pos',
            field=models.FloatField(default=0, help_text='Відступ зліва у відсотках', verbose_name='Позиція X (%)'),
        ),
        migrations.AddField(
            model_name='computer',
            name='y_pos',
            field=models.FloatField(default=0, help_text='Відступ зверху у відсотках', verbose_name='Позиція Y (%)'),
        ),
    ]
