# Generated by Django 6.0 on 2026-02-16 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0005_computer_x_pos_computer_y_pos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='x_pos',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='y_pos',
        ),
    ]
