# Generated by Django 5.2.9 on 2026-02-12 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_alter_action_id_alter_booking_id_alter_bookinglog_id_and_more'),
        ('TaskManager', '0002_computer_tariff_zone_payment_session_computer_zone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinglog',
            name='action',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дія'),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='resource',
        ),
        migrations.AddField(
            model_name='booking',
            name='computer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TaskManager.computer', verbose_name="Комп'ютер"),
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bookinglog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='status',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Action',
        ),
    ]
